#!/usr/bin/env ruby

require 'openssl';

cipher = OpenSSL::Cipher.new('AES-128-CBC');

cipher.encrypt;

keyRaw = "\x00\x11\x22\x33\x44\x55\x66\x77\x88\x99\xaa\xbb\xcc\xdd\xee\xff";
ivRaw = "\xff\xee\xdd\xcc\xbb\xaa\x99\x88\x77\x66\x55\x44\x33\x22\x11\x00";
cipher.key = keyRaw;
cipher.iv = ivRaw;

message = ARGV.join(" ");
message.strip!;

message = [0xFACEF00D,message.length,message].pack("NNA*");

output = cipher.update(message);
output = output + cipher.final;

STDOUT.write output.unpack('H*');
